[general]
import = [
    "~/.config/alacritty/themes/kaolin.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
decorations = "None"
opacity = 1
startup_mode = "Maximized"
dynamic_title = false

[font]
normal.family = "PrimeSM Nerd Font"
size = 13

[cursor]
style = { shape = "Block", blinking = "Always"}
