# Original Author:
# URL: https://github.com/sainnhe/everforest
# Filename: colors/everforest.vim
# Author: sainnhe
# Email: sainnhe@gmail.com
# License: MIT License

"attribute" = { fg = "purple", modifiers = ["italic"] }
"type" = "orange"
"type.builtin" = "yellow"
"constructor" = { fg = "green", modifiers = ["bold"] }
"constant" = "fg"
"constant.builtin" = { fg = "purple", modifiers = ["italic"] }
"constant.builtin.boolean" = "purple"
"constant.character.escape" = "green"
"string" = "aqua"
"string.regexp" = "green"
"string.special" = "yellow"
"comment" = { fg = "grey1", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = { fg = "purple", modifiers = ["italic"] }
"variable.other.member" = "blue"
"label" = "orange"
"punctuation" = "grey2"
"punctuation.special" = "blue"
"keyword" = { fg = "red", modifiers = ["italic"] }
"keyword.operator" = "orange"
"keyword.directive" = "purple"
"operator" = "orange"
"function" = { fg = "green", modifiers = ["bold"] }
"tag" = "orange"
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"module" = "yellow"
"special" = "blue"

"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

"ui.background" = { fg = "grey1", bg = "bg0" }
"ui.background.separator" = "grey0"
"ui.cursor" = { fg = "bg1", bg = "grey0" }
"ui.cursor.primary" = { fg = "bg0", bg = "fg" }
"ui.cursor.primary.insert" = { fg = "bg0", bg = "green" }
"ui.cursor.primary.select" = { fg = "bg0", bg = "red" }
"ui.cursor.match" = { fg = "fg", bg = "bg5" }
"ui.gutter" = { bg = "bg0" }
"ui.gutter.selected" = { bg = "bg1" }
"ui.linenr" = "bg5"
"ui.linenr.selected" = "grey1"
"ui.statusline" = { fg = "grey1", bg = "bg2" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "bg0", bg = "statusline2", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "bg0", bg = "statusline3", modifiers = ["bold"] }
"ui.popup" = { fg = "grey2", bg = "bg2" }
"ui.window" = { fg = "bg4", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg2" }
"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }
"ui.menu" = { fg = "fg", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.selection" = { bg = "bg2" }
"ui.selection.primary" = { bg = "bg3" }
"ui.highlight" = { bg = "bg2" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.bufferline" = { fg = "grey2", bg = "bg3" }
"ui.bufferline.active" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.bufferline.background" = { bg = "bg1" }

"warning" = "yellow"
"error" = "red"
"info" = "blue"
"hint" = "green"

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]
# background dark hard

"bg_dim" = "#1e2326"
"bg0" = "#272e33"
"bg1" = "#2e383c"
"bg2" = "#374145"
"bg3" = "#414b50"
"bg4" = "#495156"
"bg5" = "#4f5b58"
"bg_visual" = "#4c3743"
"bg_red" = "#493b40"
"bg_green" = "#3c4841"
"bg_blue" = "#384b55"
"bg_yellow" = "#45443c"

# foreground dark

fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"

grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"

statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"
